config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


  scope '/admin' do
  	resources :pages, except: :show
  end
  
  root 'pages#index'

  get '/:slug', to: 'pages#show', as: :show
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/page.rb
class Page < ApplicationRecord

  validates :slug, presence: true, uniqueness: true 


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def index
    @pages = Page.all
  end

  def new
    @page = Page.new
  end

  def show
    @page = Page.where(slug: params[:slug]).take
  end

  def create
    @page = Page.new(page_params)
 
    if @page.save
      redirect_to :action => 'index'
    else
      render 'new'
    end
  end

  private
  def page_params
    params.require(:page).permit(:title, :description, :slug, :follow, :index)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper

	def title(page_title)
	  content_for :title, page_title.to_s
	end

	def description(page_description)
	  content_for :description, page_description.to_s
	end

	def index_follow(page_index, page_follow)
	  page_index == true ? page_index ="INDEX" : page_index = "NOINDEX"
	  page_follow == true ? page_follow ="FOLLOW" : page_follow = "NOFOLLOW"
	  content_for :index_follow, (page_index.to_s + ', ' + page_follow.to_s)
	end

	def follow(page_follow)
	  content_for :follow, page_follow.to_s
	end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
   <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= yield(:title) %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "PyGoogle Demo" %>">
    <meta name="robots" content="<%= content_for?(:index_follow) ? yield(:index_follow) : "INDEX, FOLLOW" %>">
        <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

<title></title>

app/views/pages/index.html.erb
<h1>Index</h1>

<%= link_to 'Dodaj nową stronę', new_page_path  %>

<%= @pages.each do |page| %>
	<p><%= link_to page.title, show_path(page.slug)  rescue "brak linka" %> | <%= page.slug %> </p>
<% end %>

app/views/pages/new.html.erb
<%= form_with scope: :page, url: pages_path, local:true do |form| %>
  <%= @page.errors.full_messages.first if @page.errors.any? %>

  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </p>
 
  <p>
    <%= form.label :description %><br>
    <%= form.text_area :description %>
  </p>

  <p>
    <%= form.label :slug %><br>
    <%= form.text_field :slug %>
  </p>

  <p>
    <%= form.label :index %><br>
    <%= form.check_box(:index, :checked_value => "INDEX", :unchecked_value => "NOINDEX") %>
  </p>

  <p>
    <%= form.label :follow %><br>
    <%= form.check_box( :follow, :value => 'FOLLOW', :value => 'NOFOLLOW')%>
  </p>
 
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/pages/show.html.erb
<h1>Show</h1>
<% title @page.title %>
<% description @page.description %>
<% index_follow @page.index, @page.follow %>
<% follow @page.follow %>
<% # Actual view content %>
<h2><%= @page.title %></h2>
<div class='content'><%= @page.slug %></div>